name: Solar-System-Move-Plugin
version: ${project.version}
main: net.gigaclub.solarsystemmoveplugin.Main
api-version: 1.13
authors: [GigaClub]
website: https://GigaClub.net

commands:
  generateSolarSystem:
    description: /generateSolarSystem